### ISSUE TITLE
getShape is wastefu

### ISSUE THREAD

**Issue by aivision2020** [wajnryt/JerusMLDeepLearning2019#1]
@rachelash 
Looks good. Modular, readable... 

your implementation of getShape is wasteful. Looks like you create 3 images and then return just one. Consider, a dictionary of functions. Something like:

def getShape(x):
    funcs = {
        'xline': createxLine,
        'yline': createyLine,
        'diagline': createDiagLine,
    }
    return funcs[x]()

**Comment by rachelash** [comment]
ok thanks. i'll change that

‫בתאריך יום ה׳, 27 ביוני 2019 ב-12:02 מאת ‪aivision2020‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by rachelash** [comment]
I've tried these all 3 options for the return (after dictionary creation),
and no one returns the matrix:

def getShape(x):
  funcs = {
  'xline': createxLine,
  'yline': createyLine,
  'diagline': createDiagLine,
  }

  getshapeeval = eval(funcs[x])     // first option
  return getshapeeval()

  return globals()[funcs]()       // second option

  return funcs[x]   //third option




‫בתאריך יום ה׳, 27 ביוני 2019 ב-12:02 מאת ‪aivision2020‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by aivision2020** [comment]
`return funcs[x]()`

you see, funcs[x] return a function, then you need to invoke it with the parenthesise

**Comment by aivision2020** [comment]
I see, git is formating 
'''
return funcs[x]()
'''

**Comment by rachelash** [comment]
name 'funcsx' is not defined

זה מה שמקבלת.. ונשמע הגיוני..

‫בתאריך יום א׳, 30 ביוני 2019 ב-15:21 מאת ‪aivision2020‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by rachelash** [comment]
אה.... עכשיו מבינה את הבילבול.. מהמייל זה נראה אחרת מאשר דרך הגיט 
אז תודה ותכף מעלה
